version: '3.8'

services:
  rpg:
    image: ankane/pgvector:latest
    container_name: rpg_db

    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local_db

    ports:
      - '5432:5432'

    volumes:
      - rpg_data:/var/lib/postgresql/data

volumes:
  rpg_data:
